// lib/products.js
// ─────────────────────────────────────────────────────────────────
// EDIT THIS FILE to change your products, categories and prices
// ─────────────────────────────────────────────────────────────────

export const categories = [
  { id: "all",       label: "All",        icon: "🌿" },
  { id: "honey",     label: "Honey",      icon: "🍯" },
  { id: "olive-oil", label: "Olive Oil",  icon: "🫒" },
  { id: "other",     label: "Other Oils", icon: "💧" },
];

// badge options: "organic" | "new" | "sale" | null
export const products = [
  {
    id: "p1",
    name: "Greek Thyme Honey",
    description: "Pure wildflower honey from the mountains of Crete",
    origin: "Crete, Greece",
    price: 12.99,
    category: "honey",
    badge: "organic",
    stars: 4.5,
    reviews: 43,
    emoji: "🍯",
    bg: "#FFF6E0",
  },
  {
    id: "p2",
    name: "Organic Greek Olive Oil",
    description: "Cold-pressed extra virgin olive oil from Kalamata",
    origin: "Kalamata, Greece",
    price: 17.99,
    category: "olive-oil",
    badge: "organic",
    stars: 4.5,
    reviews: 156,
    emoji: "🫒",
    bg: "#EDF5E8",
  },
  {
    id: "p3",
    name: "Early Harvest Olive Oil",
    description: "Harvested early for maximum polyphenols and freshness",
    origin: "Tuscany, Italy",
    price: 19.99,
    category: "olive-oil",
    badge: "new",
    stars: 4.0,
    reviews: 38,
    emoji: "🫙",
    bg: "#EAF8EA",
  },
  {
    id: "p4",
    name: "Argan Oil",
    description: "100% pure cold-pressed Moroccan argan oil",
    origin: "Morocco",
    price: 16.99,
    category: "other",
    badge: "organic",
    stars: 4.5,
    reviews: 92,
    emoji: "💛",
    bg: "#FFF4E0",
  },
  {
    id: "p5",
    name: "Virgin Coconut Oil",
    description: "Unrefined virgin coconut oil, naturally fragrant",
    origin: "Sri Lanka",
    price: 11.99,
    category: "other",
    badge: "organic",
    stars: 4.5,
    reviews: 78,
    emoji: "🥥",
    bg: "#F0FFF5",
  },
  {
    id: "p6",
    name: "Manuka Honey",
    description: "Premium UMF-certified Manuka honey",
    origin: "New Zealand",
    price: 29.99,
    category: "honey",
    badge: "organic",
    stars: 5.0,
    reviews: 201,
    emoji: "🍯",
    bg: "#FFF0DC",
  },
  {
    id: "p7",
    name: "Avocado Oil",
    description: "Refined avocado oil with high smoke point",
    origin: "Mexico",
    price: 14.49,
    category: "other",
    badge: "new",
    stars: 4.0,
    reviews: 55,
    emoji: "🥑",
    bg: "#EDFAED",
  },
  {
    id: "p8",
    name: "Wildflower Honey",
    description: "Raw unfiltered honey from Bavarian meadows",
    origin: "Bavaria, Germany",
    price: 8.99,
    category: "honey",
    badge: null,
    stars: 4.5,
    reviews: 110,
    emoji: "🌸",
    bg: "#FFF8F0",
  },
  {
    id: "p9",
    name: "Green Stuffed Olives",
    description: "Hand-picked green olives stuffed with peppers",
    origin: "Andalusia, Spain",
    price: 8.99,
    category: "olive-oil",
    badge: null,
    stars: 4.0,
    reviews: 67,
    emoji: "🫒",
    bg: "#EFF5E8",
  },
  {
    id: "p10",
    name: "Black Seed Oil",
    description: "Cold-pressed Nigella sativa oil, traditionally used",
    origin: "Egypt",
    price: 13.50,
    category: "other",
    badge: "organic",
    stars: 4.5,
    reviews: 88,
    emoji: "🌿",
    bg: "#F5F0E8",
  },
  {
    id: "p11",
    name: "Forest Honey",
    description: "Dark forest honey with deep, rich flavour",
    origin: "Romania",
    price: 9.99,
    category: "honey",
    badge: null,
    stars: 4.0,
    reviews: 34,
    emoji: "🌳",
    bg: "#EFF8F0",
  },
  {
    id: "p12",
    name: "Extra Virgin Olive Oil",
    description: "Award-winning single-origin extra virgin olive oil",
    origin: "Cordoba, Spain",
    price: 15.99,
    category: "olive-oil",
    badge: "organic",
    stars: 4.5,
    reviews: 142,
    emoji: "🍶",
    bg: "#EAF5E8",
  },
];
